INSERT INTO permissions (id, code, resource, action, description) VALUES
(gen_random_uuid(), 'TENANT_READ', 'TENANT', 'READ', 'Read tenant info'),
(gen_random_uuid(), 'TENANT_WRITE', 'TENANT', 'WRITE', 'Modify tenant'),
(gen_random_uuid(), 'USER_READ', 'USER', 'READ', 'Read users'),
(gen_random_uuid(), 'USER_WRITE', 'USER', 'WRITE', 'Create/update users'),
(gen_random_uuid(), 'USER_DELETE', 'USER', 'DELETE', 'Delete users'),
(gen_random_uuid(), 'ORG_READ', 'ORG', 'READ', 'Read org structure'),
(gen_random_uuid(), 'ORG_WRITE', 'ORG', 'WRITE', 'Modify org structure'),
(gen_random_uuid(), 'KPI_TEMPLATE_READ', 'KPI_TEMPLATE', 'READ', 'Read KPI templates'),
(gen_random_uuid(), 'KPI_TEMPLATE_WRITE', 'KPI_TEMPLATE', 'WRITE', 'Create/update templates'),
(gen_random_uuid(), 'KPI_READ', 'KPI', 'READ', 'Read KPIs'),
(gen_random_uuid(), 'KPI_WRITE', 'KPI', 'WRITE', 'Create/update KPIs'),
(gen_random_uuid(), 'KPI_DELETE', 'KPI', 'DELETE', 'Delete KPIs'),
(gen_random_uuid(), 'KPI_APPROVE', 'KPI', 'APPROVE', 'Approve/reject KPIs'),
(gen_random_uuid(), 'KPI_VALUE_WRITE', 'KPI_VALUE', 'WRITE', 'Record KPI progress'),
(gen_random_uuid(), 'GOAL_READ', 'GOAL', 'READ', 'Read goals'),
(gen_random_uuid(), 'GOAL_WRITE', 'GOAL', 'WRITE', 'Create/update goals'),
(gen_random_uuid(), 'DASHBOARD_READ', 'DASHBOARD', 'READ', 'View dashboards'),
(gen_random_uuid(), 'DASHBOARD_WRITE', 'DASHBOARD', 'WRITE', 'Create/modify dashboards'),
(gen_random_uuid(), 'REPORT_READ', 'REPORT', 'READ', 'View reports'),
(gen_random_uuid(), 'REPORT_GENERATE', 'REPORT', 'EXECUTE', 'Generate reports'),
(gen_random_uuid(), 'ALERT_READ', 'ALERT', 'READ', 'View alert rules'),
(gen_random_uuid(), 'ALERT_WRITE', 'ALERT', 'WRITE', 'Create/modify alert rules'),
(gen_random_uuid(), 'AUDIT_READ', 'AUDIT', 'READ', 'View audit logs'),
(gen_random_uuid(), 'AI_QUERY', 'AI', 'EXECUTE', 'Use AI assistant'),
(gen_random_uuid(), 'LEADERBOARD_READ', 'LEADERBOARD', 'READ', 'View leaderboards'),
(gen_random_uuid(), 'INTEGRATION_MANAGE', 'INTEGRATION', 'WRITE', 'Manage integrations');
